### ISSUE TITLE
   1) <FuelSavingsPage /> should contain <FuelSavingsForm />:      TypeError: Cannot read property 'props' of undefined

### ISSUE THREAD

**Issue by flykye** [coryhouse/react-slingshot#130]
1) <FuelSavingsPage /> should contain <FuelSavingsForm />:
     TypeError: Cannot read property 'props' of undefined
      at FuelSavingsPage (FuelSavingsPage.js:10:24)
      at [object Object].ReactCompositeComponentMixin._constructComponentWithoutOwner (node_modules/react/lib/ReactCompositeComponent.js:250:14)
      at [object Object].ReactCompositeComponentMixin.mountComponent (node_modules/react/lib/ReactCompositeComponent.js:159:21)
      at [object Object].ReactShallowRenderer._render (node_modules/react/lib/ReactTestUtils.js:385:14)
      at _batchedRender (node_modules/react/lib/ReactTestUtils.js:366:12)
      at ReactDefaultBatchingStrategyTransaction.Mixin.perform (node_modules/react/lib/Transaction.js:136:20)
      at Object.ReactDefaultBatchingStrategy.batchedUpdates (node_modules/react/lib/ReactDefaultBatchingStrategy.js:63:19)
      at Object.batchedUpdates (node_modules/react/lib/ReactUpdates.js:97:20)
      at [object Object].ReactShallowRenderer.render (node_modules/react/lib/ReactTestUtils.js:359:16)
      at [object Object].render (node_modules/enzyme/build/react-compat.js:146:39)
      at new ShallowWrapper (node_modules/enzyme/build/ShallowWrapper.js:81:21)
      at shallow (node_modules/enzyme/build/shallow.js:21:10)
      at Context.<anonymous> (FuelSavingsPage.spec.js:14:21)

**Comment by apostopher** [comment]
I'm getting the same error

**Comment by j5v** [comment]
In `FuelSavingsResults.js`, `FuelSavingsPage()` currently has no scope for the props; `this.props` is undefined. This can be fixed by adding `props` to the parameters for the function, then using `props` instead of `this.props`, to give:
```JavaScript
export const FuelSavingsPage = (props) => {
  return (
    <FuelSavingsForm
      saveFuelSavings={props.actions.saveFuelSavings}
      calculateFuelSavings={props.actions.calculateFuelSavings}
      appState={props.appState}
    />
  );
};
```
Please check this actually works before committing; I'm deleting the example code for my own project, but just wanted to get the example working first.

**Comment by coryhouse** [comment]
Whoops! Fixed. Sorry about that.
