### ISSUE TITLE
Cannot find module './NumberFormatter'

### ISSUE THREAD

**Issue by tleen** [coryhouse/react-slingshot#2]
From colone/install/run via directions, did not seem to impact functionality:

Error: Cannot find module './NumberFormatter'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/tml/projects/react-slingshot/src/businessLogic/numberFormatter.spec.js:5:24)
    at Module._compile (module.js:425:26)
    at normalLoader (/home/tml/projects/react-slingshot/node_modules/babel-core/lib/api/register/node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/tml/projects/react-slingshot/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at /home/tml/projects/react-slingshot/node_modules/mocha/lib/mocha.js:216:27
    at Array.forEach (native)
    at Mocha.loadFiles (/home/tml/projects/react-slingshot/node_modules/mocha/lib/mocha.js:213:14)
    at Mocha.run (/home/tml/projects/react-slingshot/node_modules/mocha/lib/mocha.js:453:10)
    at loadAndRun (/home/tml/projects/react-slingshot/node_modules/mocha/bin/_mocha:349:22)
    at Object.<anonymous> (/home/tml/projects/react-slingshot/node_modules/mocha/bin/_mocha:366:3)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:138:18)
    at node.js:974:3

**Comment by coryhouse** [comment]
Ah, had a casing issue in one of the test files. Resolved. Thanks for the heads up!
