### ISSUE TITLE
Tests coverage

### ISSUE THREAD

**Issue by SebDez** [coryhouse/react-slingshot#223]
Hi coryhouse !

First I would like to thank you for this great starter project.

I recently start to develop with this and when I wanted to generate my test coverage I realized that I've got a coverage at 100% while I haven't done any test.

After some researches, I found that the coverage was only applied on .spec files, so only js files with a spec file defined are registered for the coverage.

So I did this in my package.json :

```
"test": "mocha tools/testSetup.js \"src/app/**/*.js\" --reporter progress",
"test:cover": "babel-node node_modules/isparta/bin/isparta cover --root src --report html node_modules/mocha/bin/_mocha -- --require ./tools/testSetup.js \"src/app/**/*.js\" --reporter progress"
```

And now I have a full coverage on all my js files, and a correct percentage value (- which is far from 100% !).

**Note** : it seems that mocha is unable to load index.js and webpack-public-path.js, so I put my all app in a 'app' subfolder.

I hope this can be usefull to somebody ;)

**Comment by coryhouse** [comment]
Interesting. Thanks for pointing this out!  Would you be willing to submit a pull request that contains a suggested fix? 

Also, why did you create the app subfolder under app?

**Comment by nibblesnbits** [comment]
I'm having this same issue, but @SebDez's fix of removing `.spec` doesn't work for me; it causes NPM to throw an error:

```bash
> new-project@0.1.0 test:cover C:\dump\react-slingshot
> babel-node node_modules/isparta/bin/isparta cover --root src --report html node_modules/mocha/bin/_mocha -- --require ./tools/testSetup.js "src/**/*.js" --reporter progress


npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "test:cover"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE
npm ERR! new-project@0.1.0 test:cover: `babel-node node_modules/isparta/bin/isparta cover --root src --report html node_modules/mocha/bin/_mocha -- --require ./tools/testSetup.js "src/**/*.js" --reporter progress`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the new-project@0.1.0 test:cover script 'babel-node node_modules/isparta/bin/isparta cover --root src --report html node_modules/mocha/bin/_mocha -- --require ./tools/testSetup.js "src/**/*.js" --reporter progress'.
npm ERR! This is most likely a problem with the new-project package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node node_modules/isparta/bin/isparta cover --root src --report html node_modules/mocha/bin/_mocha -- --require ./tools/testSetup.js "src/**/*.js" --reporter progress
npm ERR! You can get their info via:
npm ERR!     npm owner ls new-project
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\dump\react-slingshot\npm-debug.log
```

npm-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'test:cover' ]
2 info using npm@3.3.6
3 info using node@v5.0.0
4 verbose run-script [ 'pretest:cover', 'test:cover', 'posttest:cover' ]
5 info lifecycle new-project@0.1.0~pretest:cover: new-project@0.1.0
6 silly lifecycle new-project@0.1.0~pretest:cover: no script for pretest:cover, continuing
7 info lifecycle new-project@0.1.0~test:cover: new-project@0.1.0
8 verbose lifecycle new-project@0.1.0~test:cover: unsafe-perm in lifecycle true
9 verbose lifecycle new-project@0.1.0~test:cover: PATH: C:\Users\stephen.collins\AppData\Roaming\nvm\v5.0.0\node_modules\npm\bin\node-gyp-bin;C:\dump\react-slingshot\node_modules\.bin;C:\Users\stephen.collins\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\cmd;C:\Program Files\ConEmu\ConEmu\Scripts;C:\Program Files\ConEmu;C:\Program Files\ConEmu\ConEmu;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\NTRU Cryptosystems\NTRU TCG Software Stack\bin;C:\Program Files\NTRU Cryptosystems\NTRU TCG Software Stack\bin;C:\Program Files\Dell\Dell Data Protection\Access\Advanced\Wave\Gemalto\Access Client\v5;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files\Microsoft SQL Server\120\Tools\Binn;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Program Files\Git\cmd;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn;C:\Users\stephen.collins\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\HashiCorp\Vagrant\bin;C:\Program Files\dotnet;C:\nuget;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn;C:\Program Files\Microsoft SQL Server\110\Tools\Binn;C:\Program Files\Microsoft SQL Server\110\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio;C:\Users\stephen.collins\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\stephen.collins\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\nuget;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
10 verbose lifecycle new-project@0.1.0~test:cover: CWD: C:\dump\react-slingshot
11 silly lifecycle new-project@0.1.0~test:cover: Args: [ '/d /s /c',
11 silly lifecycle   'babel-node node_modules/isparta/bin/isparta cover --root src --report html node_modules/mocha/bin/_mocha -- --require ./tools/testSetup.js "src/**/*.js" --reporter progress' ]
12 silly lifecycle new-project@0.1.0~test:cover: Returned: code: 1  signal: null
13 info lifecycle new-project@0.1.0~test:cover: Failed to exec test:cover script
14 verbose stack Error: new-project@0.1.0 test:cover: `babel-node node_modules/isparta/bin/isparta cover --root src --report html node_modules/mocha/bin/_mocha -- --require ./tools/testSetup.js "src/**/*.js" --reporter progress`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\stephen.collins\AppData\Roaming\nvm\v5.0.0\node_modules\npm\lib\utils\lifecycle.js:233:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\stephen.collins\AppData\Roaming\nvm\v5.0.0\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:818:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid new-project@0.1.0
16 verbose cwd C:\dump\react-slingshot
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "test:cover"
19 error node v5.0.0
20 error npm  v3.3.6
21 error code ELIFECYCLE
22 error new-project@0.1.0 test:cover: `babel-node node_modules/isparta/bin/isparta cover --root src --report html node_modules/mocha/bin/_mocha -- --require ./tools/testSetup.js "src/**/*.js" --reporter progress`
22 error Exit status 1
23 error Failed at the new-project@0.1.0 test:cover script 'babel-node node_modules/isparta/bin/isparta cover --root src --report html node_modules/mocha/bin/_mocha -- --require ./tools/testSetup.js "src/**/*.js" --reporter progress'.
23 error This is most likely a problem with the new-project package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     babel-node node_modules/isparta/bin/isparta cover --root src --report html node_modules/mocha/bin/_mocha -- --require ./tools/testSetup.js "src/**/*.js" --reporter progress
23 error You can get their info via:
23 error     npm owner ls new-project
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by SebDez** [comment]
Hi all !

I just clone the project and effectively I've got the same issue.
It seems that isparta have some issues with Istanbul 0.4.5.

I have set istanbul in my package.json with version 0.4.4.

But from there you will get the same error, so you need to put all the sources in an 'app' (or whatever) subfolder.

**Why did I use an 'app' subfolder ?**

Because I don't know how to ignore a file with mocha, I think it's not possible but I'm not sure about that. :/

So, I have the following :

> - src/
> -- app/
> ---actions
> ---componenets
> --- etc.
> --index.js
> --routes.js
> --webpack-public-path.js

I did like this because the index.js, routes.js and webpack-public-path.js make mocha crash.

Try this and tell me if it works for you as it works for me ;)

NOTE : don't forget to change your path in imports to access files in app folder

**Comment by kwelch** [comment]
PR #294 included the change above. Does it also then close out this issue?

**Comment by silentbobbert** [comment]
I get the same issue on Windows, after doing a clean clone.

![image](https://cloud.githubusercontent.com/assets/3257988/21803046/30be81dc-d720-11e6-9c43-1fbda4fe7532.png)

Steps to repro:

1. Clone
2. npm run setup
3. npm run test:cover
4. error messages

I tried running it in the terminal in VS Code and a normal command prompt with the same result.

The tests run fine with running "test" or "test:watch", its only when you try to wrap the tests with isparta?

**Comment by anton-tarasov-qs** [comment]
The issue still exists for me too. I get the same results that silentbobbert has :(

**Comment by mherodev** [comment]
Ah yes, the issue occurs here on OSX as well. I commented in the other test coverage issue.

I'll have to dig into this tomorrow.

**Comment by mherodev** [comment]
The Istanbul version upgrade PR tackles half of the issue. The `mocha` path issue appears to be a node version issue.  Switching to `node v6.3.0` fixes the error associated with pointing at node_module's `mocha` directly.

**Comment by mherodev** [comment]
The PR I just submitted (https://github.com/coryhouse/react-slingshot/pull/358) should resolve this issue as well.

**Comment by coryhouse** [comment]
PR #358 has been merged. Thanks @mherodev! Once someone on Windows reports back that they're in good shape now I'll close this.

**Comment by nibblesnbits** [comment]
I'm on Windows 10, Node v6.5.0.

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'test:cover' ]
2 info using npm@3.10.3
3 info using node@v6.5.0
4 verbose run-script [ 'pretest:cover', 'test:cover', 'posttest:cover' ]
5 info lifecycle react-slingshot@5.0.0~pretest:cover: react-slingshot@5.0.0
6 silly lifecycle react-slingshot@5.0.0~pretest:cover: no script for pretest:cover, continuing
7 info lifecycle react-slingshot@5.0.0~test:cover: react-slingshot@5.0.0
8 verbose lifecycle react-slingshot@5.0.0~test:cover: unsafe-perm in lifecycle true
9 verbose lifecycle react-slingshot@5.0.0~test:cover: PATH: C:\Users\stephen.collins\AppData\Roaming\nvm\v6.5.0\node_modules\npm\bin\node-gyp-bin;C:\dump\react-slingshot\node_modules\.bin;C:\Program Files\nodejs;C:\Users\stephen.collins\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\cmd;C:\Program Files\ConEmu\ConEmu\Scripts;C:\Program Files\ConEmu;C:\Program Files\ConEmu\ConEmu;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Python27;C:\Python27\Scripts;C:\Program Files\HP_Fortify\HP_Fortify_SCA_and_Apps_16.11\bin;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\NTRU Cryptosystems\NTRU TCG Software Stack\bin;C:\Program Files\NTRU Cryptosystems\NTRU TCG Software Stack\bin;C:\Program Files\Dell\Dell Data Protection\Access\Advanced\Wave\Gemalto\Access Client\v5;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files\Microsoft SQL Server\120\Tools\Binn;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Program Files\Git\cmd;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn;C:\Users\stephen.collins\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\HashiCorp\Vagrant\bin;C:\Program Files\dotnet;C:\nuget;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn;C:\Program Files\Microsoft SQL Server\110\Tools\Binn;C:\Program Files\Microsoft SQL Server\110\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio;C:\Go\bin;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\Yarn\bin;C:\Users\stephen.collins\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\stephen.collins\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\nuget;C:\Users\stephen.collins\AppData\Local\Yarn\.bin;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
10 verbose lifecycle react-slingshot@5.0.0~test:cover: CWD: C:\dump\react-slingshot
11 silly lifecycle react-slingshot@5.0.0~test:cover: Args: [ '/d /s /c',
11 silly lifecycle   'babel-node node_modules/isparta/bin/isparta cover --root src --report html mocha -- --require ./tools/testSetup.js src/**/*.spec.js --reporter progress' ]
12 silly lifecycle react-slingshot@5.0.0~test:cover: Returned: code: 1  signal: null
13 info lifecycle react-slingshot@5.0.0~test:cover: Failed to exec test:cover script
14 verbose stack Error: react-slingshot@5.0.0 test:cover: `babel-node node_modules/isparta/bin/isparta cover --root src --report html mocha -- --require ./tools/testSetup.js src/**/*.spec.js --reporter progress`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\stephen.collins\AppData\Roaming\nvm\v6.5.0\node_modules\npm\lib\utils\lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\stephen.collins\AppData\Roaming\nvm\v6.5.0\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid react-slingshot@5.0.0
16 verbose cwd C:\dump\react-slingshot
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "test:cover"
19 error node v6.5.0
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error react-slingshot@5.0.0 test:cover: `babel-node node_modules/isparta/bin/isparta cover --root src --report html mocha -- --require ./tools/testSetup.js src/**/*.spec.js --reporter progress`
22 error Exit status 1
23 error Failed at the react-slingshot@5.0.0 test:cover script 'babel-node node_modules/isparta/bin/isparta cover --root src --report html mocha -- --require ./tools/testSetup.js src/**/*.spec.js --reporter progress'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the react-slingshot package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     babel-node node_modules/isparta/bin/isparta cover --root src --report html mocha -- --require ./tools/testSetup.js src/**/*.spec.js --reporter progress
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs react-slingshot
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls react-slingshot
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by coryhouse** [comment]
Sorry to hear. The nwb project uses the same testing stack and code coverage works fine there, so if someone has time, reviewing their approach should show the issue. https://github.com/insin/nwb

Sorry, I'm currently buried.

**Comment by mherodev** [comment]
After adopting redux-saga, I found that the current architecture wasn't supporting coverage for generators for some reason, but that hiccup went away when I switched to `nyc` from `isparta`. 

It's probably best to wait on a Jest implementation, however.

**Comment by kwelch** [comment]
`test:cover` looks good for me on the new `jest` branch. 

I would appreciate it, if @nibblesnbits could review with Windows 10 and let me know if the move to jest resolves that issue.

I `expect` it would, but prior to merging the jest branch I would love to have that confirmed

**Comment by mherodev** [comment]
`expect` he says

**Comment by kwelch** [comment]
I have been working in tests for a very long time, I really had to do it.

**Comment by silentbobbert** [comment]
![image](https://cloud.githubusercontent.com/assets/3257988/22585034/9d2f724c-e9ed-11e6-88bd-0deaf95a7f0f.png)

I think @kwelch has now got a test runner that works on Windows with coverage enabled 👍

**Comment by coryhouse** [comment]
Thanks to @kwelch hard work, the 6.0 release moved us to Jest with its built in code coverage.

**Comment by mherodev** [comment]
Used his PR to move Jest into our project, too 💃
