### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mlinko** [coryhouse/react-slingshot#293]
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'setup' ]
2 info using npm@3.10.8
3 info using node@v7.0.0
4 verbose run-script [ 'presetup', 'setup', 'postsetup' ]
5 info lifecycle react-slingshot@5.0.0~presetup: react-slingshot@5.0.0
6 silly lifecycle react-slingshot@5.0.0~presetup: no script for presetup, continuing
7 info lifecycle react-slingshot@5.0.0~setup: react-slingshot@5.0.0
8 verbose lifecycle react-slingshot@5.0.0~setup: unsafe-perm in lifecycle true
9 verbose lifecycle react-slingshot@5.0.0~setup: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;E:\Privatni Projekti\book-store\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\MSBuild\14.0\bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools;C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools;C:\Program Files (x86)\Windows Kits\10\bin\x86;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\nodejs\;C:\Program Files (x86)\Yarn\bin;C:\Program Files\Git\cmd;C:\Users\OunknownO\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Users\OunknownO\.dnx\bin;C:\Users\OunknownO\AppData\Local\Microsoft\WindowsApps;C:\Users\OunknownO\AppData\Roaming\npm;C:\Users\OunknownO\AppData\Local\Yarn\.bin
10 verbose lifecycle react-slingshot@5.0.0~setup: CWD: E:\Privatni Projekti\book-store
11 silly lifecycle react-slingshot@5.0.0~setup: Args: [ '/d /s /c',
11 silly lifecycle   'node tools/setup/setupMessage.js && npm install && node tools/setup/setup.js' ]
12 silly lifecycle react-slingshot@5.0.0~setup: Returned: code: 1  signal: null
13 info lifecycle react-slingshot@5.0.0~setup: Failed to exec setup script
14 verbose stack Error: react-slingshot@5.0.0 setup: `node tools/setup/setupMessage.js && npm install && node tools/setup/setup.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid react-slingshot@5.0.0
16 verbose cwd E:\Privatni Projekti\book-store
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "setup"
19 error node v7.0.0
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error react-slingshot@5.0.0 setup: `node tools/setup/setupMessage.js && npm install && node tools/setup/setup.js`
22 error Exit status 1
23 error Failed at the react-slingshot@5.0.0 setup script 'node tools/setup/setupMessage.js && npm install && node tools/setup/setup.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the react-slingshot package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node tools/setup/setupMessage.js && npm install && node tools/setup/setup.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs react-slingshot
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls react-slingshot
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

When I try "npm install" I got this error

**Comment by coryhouse** [comment]
Can you try moving this to a path that doesn't contain spaces? I've seen that cause issues on windows.

**Comment by mlinko** [comment]
that was the issue
