### ISSUE TITLE
Specs fail with - matchMedia not present, legacy browsers require a polyfill

### ISSUE THREAD

**Issue by mdomasevicius** [coryhouse/react-slingshot#432]
I am using `react-slingshot` with [ant design](https://github.com/ant-design/ant-design) and whenever I wish to test a component which has `ant design` components in it - tests fail with:

```
FAIL  src\customer\detail\CustomerDetailCard.spec.js
  ● Test suite failed to run

    matchMedia not present, legacy browsers require a polyfill

      at new MediaQueryDispatch (node_modules\enquire.js\src\MediaQueryDispatch.js:15:15)
      at Object.<anonymous> (node_modules\enquire.js\src\index.js:2:18)
      at Object.<anonymous> (node_modules\react-slick\lib\slider.js:37:38)
      at Object.<anonymous> (node_modules\react-slick\lib\index.js:3:18)
      at Object.<anonymous> (node_modules\antd\lib\carousel\index.js:32:19)
      at Object.<anonymous> (node_modules\antd\lib\index.js:106:17)
      at Object.<anonymous> (src\customer\detail\CustomerDetailCard.js:2:39)
      at Object.<anonymous> (src\customer\detail\CustomerDetailCard.spec.js:2:53)
      at process._tickCallback (internal\process\next_tick.js:109:7)
```

I did not find how to configure testing facilities for `react-slingshot` to fix this issue.

Snippet:
```
import React from 'react';
import CustomerDetailCard from './CustomerDetailCard';
import {shallow} from 'enzyme';

describe('CustomerDetailCard', () => {
    it('should have 6 rows for customer data', () => {
        const wrapper = shallow(<CustomerDetailCard />);
        const found = wrapper.findWhere(n => n.prop('className') === 'row').length;

        expect(found).toBe(6);
    });
});
```

**Comment by kwelch** [comment]
Has the ant design components worked within any development? Based on the error it is in need of a polyfill. If it works when running the dev-server, then one of the polyfills packaged with react-slingshot is required to use that library.

**Comment by mdomasevicius** [comment]
@kwelch I guess I found some info related to this issue [https://github.com/ant-design/ant-design/issues/3308](https://github.com/ant-design/ant-design/issues/3308)

**Comment by kwelch** [comment]
Glad you were able to find resolution. Since this is specific to `ant-design` and not `react-slingshot` I am closing.
