### ISSUE TITLE
Cannot read property 'error' of undefined when running 'npm run start'

### ISSUE THREAD

**Issue by wang3g** [coryhouse/react-slingshot#438]
Hi, I have followed every step as stated but received the following error when I tried to run the demo

Mac-mini:react-slingshot jack$ npm run start

> react-slingshot@0.1.0 prestart /Users/jackwang/react-slingshot
> npm-run-all --parallel start-message

> react-slingshot@0.1.0 start-message /Users/jackwang/react-slingshot
> babel-node tools/startMessage.js

/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126
      if (!option) this.log.error("Unknown option: " + alias + "." + key, ReferenceError);
                           ^

TypeError: Cannot read property 'error' of undefined
    at OptionManager.mergeOptions (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:28)
    at OptionManager.addConfig (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
    at OptionManager.findConfigs (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:168:35)
    at OptionManager.init (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
    at compile (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:117:22)
    at normalLoader (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:199:14)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)

Node version: v4.7.0

npm version: 2.15.11

Operating system: OS X 10.11.5

**Comment by coryhouse** [comment]
I suggest updating Node and npm and trying again.

**Comment by wang3g** [comment]
The problem is gone after I switched to Node V 6.10.2. Thanks a lot!

**Comment by coryhouse** [comment]
Great to hear! 👍
