### ISSUE TITLE
Error: Cannot find module 'rimraf' - even after manually installing it and re-running npm run setup

### ISSUE THREAD

**Issue by sscholle** [coryhouse/react-slingshot#482]
Node version:
6.10.1
npm version:
5.4.2
Operating system:
macOs 10.12.6
Command line used:
npm run setup
Steps to reproduce:
1. fork repo
2. clone forked repo
3. run: npm run setup
4. setup exits with errors

Dump of log file:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'setup' ]
2 info using npm@5.4.2
3 info using node@v6.10.1
4 verbose run-script [ 'presetup', 'setup', 'postsetup' ]
5 info lifecycle react-slingshot@7.0.0~presetup: react-slingshot@7.0.0
6 info lifecycle react-slingshot@7.0.0~setup: react-slingshot@7.0.0
7 verbose lifecycle react-slingshot@7.0.0~setup: unsafe-perm in lifecycle true
8 verbose lifecycle react-slingshot@7.0.0~setup: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/sebastians/repo/React.js/react-slingshot/node_modules/.bin:/Users/Shared/android/platform-tools:/Users/Shared/android/tools/bin:/Users/sebastians/MyInstalls/mongodb/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
9 verbose lifecycle react-slingshot@7.0.0~setup: CWD: /Users/sebastians/repo/React.js/react-slingshot
10 silly lifecycle react-slingshot@7.0.0~setup: Args: [ '-c',
10 silly lifecycle   'node tools/setup/setupMessage.js && npm install && node tools/setup/setup.js' ]
11 silly lifecycle react-slingshot@7.0.0~setup: Returned: code: 1  signal: null
12 info lifecycle react-slingshot@7.0.0~setup: Failed to exec setup script
13 verbose stack Error: react-slingshot@7.0.0 setup: `node tools/setup/setupMessage.js && npm install && node tools/setup/setup.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:191:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:886:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid react-slingshot@7.0.0
15 verbose cwd /Users/sebastians/repo/React.js/react-slingshot
16 verbose Darwin 16.7.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "setup"
18 verbose node v6.10.1
19 verbose npm  v5.4.2
20 error code ELIFECYCLE
21 error errno 1
22 error react-slingshot@7.0.0 setup: `node tools/setup/setupMessage.js && npm install && node tools/setup/setup.js`
22 error Exit status 1
23 error Failed at the react-slingshot@7.0.0 setup script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

*** for some reason the npm install isn't installing app deps/. Where are all the node modules going?

**Comment by sscholle** [comment]
[SOLVED] restarted macOs - possibly an npm caching failure.
