### ISSUE TITLE
Something killing the npm start process: Error: EPERM: operation not permitted, scandir...

### ISSUE THREAD

**Issue by syrys** [coryhouse/react-slingshot#548]
So, im new to this repo, was playing around with it today and i found the following issue. Demo app builds and runs fine. but when you are editing files (while `npm start` process running in the background), sometimes the process crashes and you see the following output on the command line:

````
...
...
webpack built 3526873400bd03ea1758 in 592ms
webpack building...
✓ Clean (22:38:14)
webpack built 93b985d4897ec40ced4b in 606ms
Error: EPERM: operation not permitted, scandir '__DIR_OF_PROJECT__\src\components\AboutPage.js___jb_old___'
    at Object.fs.readdirSync (fs.js:904:18)
    at GlobSync._readdir (__DIR_OF_PROJECT__\node_modules\glob\sync.js:288:41)
    at GlobSync._readdir (__DIR_OF_PROJECT__\node_modules\eslint\lib\util\glob.js:59:36)
    at GlobSync._readdirInGlobStar (__DIR_OF_PROJECT__\node_modules\glob\sync.js:267:20)
    at GlobSync._readdir (__DIR_OF_PROJECT__\node_modules\glob\sync.js:276:17)
    at GlobSync._readdir (__DIR_OF_PROJECT__\node_modules\eslint\lib\util\glob.js:59:36)
    at GlobSync._processReaddir (__DIR_OF_PROJECT__\node_modules\glob\sync.js:137:22)
    at GlobSync._process (__DIR_OF_PROJECT__\node_modules\glob\sync.js:132:10)
    at GlobSync._processGlobStar (__DIR_OF_PROJECT__\node_modules\glob\sync.js:380:10)
    at GlobSync._process (__DIR_OF_PROJECT__\node_modules\glob\sync.js:130:10)

__DIR_OF_PROJECT__>
````
* replaced my directory path with `__DIR_OF_PROJECT__` above

OS: Windows 10
`npm -v`: 5.6.0
`node -v`: v9.5.0

Its a fresh clone of this repo.

any ideas? O.o

**Comment by syrys** [comment]
Intellij IDE un-checking the following helps:
`File->Settings->System Settings->sychronization->use safe write`
(this is actually noted in the readme, but it doesnt really say it would cause errors and kill the node process haha)

Can we not have a way around this? Its not really nice to ask everyone to uncheck something in their IDE configs just for one codebase/app.  couldnt we have some other exception that can be coded in? I tested out couple of other react starter projects recently, and this is the first time ive come across this issue, could others have made some solution for this problem that can be integrated here?

**Comment by coryhouse** [comment]
This issue is mentioned in the [initial setup](https://github.com/coryhouse/react-slingshot#initial-machine-setup). I'm open to suggestions if anyone knows a workaround. When I added this, other boilerplates were suggesting the same.
