### ISSUE TITLE
TypeError crashes npm start on every rebuild 

### ISSUE THREAD

**Issue by ohenrik** [coryhouse/react-slingshot#553]
I’m getting a strange error that crashes my `npm start -s` command every time i save a file.

Here is the output:

```
 PASS  src/components/containers/FuelSavingsPage.spec.js
 PASS  src/store/store.spec.js
 PASS  src/reducers/fuelSavingsReducer.spec.js

Test Suites: 3 passed, 3 total
Tests:       10 passed, 10 total
Snapshots:   2 passed, 2 total
Time:        0.751s, estimated 1s
Ran all test suites related to changed files.

Watch Usage: Press w to show more.
/home/ohenrik/Projects/amplify_charts/node_modules/eslint-plugin-import/lib/ExportMap.js:32
    this.dependencies.forEach(dep => size += dep().size)
                                             ^
TypeError: Cannot read property 'size' of null
    at dependencies.forEach.dep (/home/ohenrik/Projects/amplify_charts/node_modules/eslint-plugin-import/lib/ExportMap.js:32:46)
    at Map.forEach (<anonymous>)
    at ExportMap.get size [as size] (/home/ohenrik/Projects/amplify_charts/node_modules/eslint-plugin-import/lib/ExportMap.js:32:23)
    at processBodyStatement (/home/ohenrik/Projects/amplify_charts/node_modules/eslint-plugin-import/lib/rules/rules/namespace.js:59:30)
    at Array.forEach (<anonymous>)
    at Linter.Program (/home/ohenrik/Projects/amplify_charts/node_modules/eslint-plugin-import/lib/rules/rules/namespace.js:77:14)
    at emitOne (events.js:121:20)
    at Linter.emit (events.js:211:7)
    at NodeEventGenerator.applySelector (/home/ohenrik/Projects/amplify_charts/node_modules/eslint/lib/util/node-event-generator.js:265:26)
    at NodeEventGenerator.applySelectors (/home/ohenrik/Projects/amplify_charts/node_modules/eslint/lib/util/node-event-generator.js:294:22)
webpack built e5a69ec3f7d478577e4c in 874ms
``` 

I have absolutely no idea where this is coming from, any help with debugging is appreciated :-/

Node version:
8.11.1

npm version:
5.6.0

Operating system:
Ubuntu 16.04.4 LTS

Command line used:
zsh

Steps to reproduce:
Well... i have no idea, it just suddenly started to crash on every rebuild.

**Comment by ohenrik** [comment]
ok, i have figured out that it crashes due to D3...

`import * as d3 from "d3";`

So there a re a number a proposed solutions, however webpack is changing so fast that currently i cannot find any that works...

If any one wants to repproduce this just install d3 `npm install d3` and then use `import * as d3 from "d3";`.

**Comment by nickytonline** [comment]
Feel free to continue the discussion here, but closing this as it seems to be a d3/webpack issue and not a react-slingshot issue.
