### ISSUE TITLE
chokidar Unhandled 'error' event on Ubuntu 15.10

### ISSUE THREAD

**Issue by mmacedoeu** [coryhouse/react-slingshot#6]
Looks like chokidar is not working under Ubuntu. Got this Unhandled error:

    npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
    npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.6
    npm WARN react-slingshot@1.0.0 No repository field.

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: watch src ENOSPC
    at exports._errnoException (util.js:870:11)
    at FSWatcher.start (fs.js:1234:19)
    at Object.fs.watch (fs.js:1262:11)
    at createFsWatchInstance (/home/macedo/w/react-slingshot/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/macedo/w/react-slingshot/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/macedo/w/react-slingshot/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/home/macedo/w/react-slingshot/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at FSWatcher.<anonymous> (/home/macedo/w/react-slingshot/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at FSWatcher.<anonymous> (/home/macedo/w/react-slingshot/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:82:15)

npm ERR! Linux 4.2.0-22-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "open"
npm ERR! node v4.2.4
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! react-slingshot@1.0.0 open: `node tools/server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-slingshot@1.0.0 open script 'node tools/server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-slingshot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node tools/server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-slingshot
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-slingshot
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/macedo/w/react-slingshot/npm-debug.log

npm ERR! Linux 4.2.0-22-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.4
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! react-slingshot@1.0.0 start: `parallelshell "npm run test" "npm run open"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-slingshot@1.0.0 start script 'parallelshell "npm run test" "npm run open"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-slingshot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     parallelshell "npm run test" "npm run open"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-slingshot
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-slingshot
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/macedo/w/react-slingshot/npm-debug.log
macedo@macedo-Z97-D3H:~/w/react-slingshot$ 

  [▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬]

  29 passing (32ms)
```

**Comment by coryhouse** [comment]
Does this work?

`npm run open`

**Comment by mmacedoeu** [comment]
Same error.

**Comment by coryhouse** [comment]
Believe this is related to browser-sync. Can you see if the fix in this thread does the trick? https://github.com/BrowserSync/browser-sync/issues/224

**Comment by coryhouse** [comment]
More specifically, I believe this is your issue on Linux: http://stackoverflow.com/questions/16748737/grunt-watch-error-waiting-fatal-error-watch-enospc

**Comment by mmacedoeu** [comment]
Confirmed the trick on BrowserSync. It's working now !
