### ISSUE TITLE
Error running 'npm install'

### ISSUE THREAD

**Issue by macq55666** [coryhouse/react-slingshot#635]
Current environemnt
`# node --version
v9.11.2
# npm --version
6.12.0`

I get the following error:
`# npm install node -g

> node@12.12.0 preinstall /usr/lib/node_modules/node
> node installArchSpecificPackage

internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module '/usr/lib/node_modules/node/installArchSpecificPackage'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node@12.12.0 preinstall: `node installArchSpecificPackage`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node@12.12.0 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-10-25T13_14_43_151Z-debug.log`

I tried deleting node_modules and trying again but still got the same error.

**Comment by sybarita** [comment]
Did you ever figure this out?
