### ISSUE TITLE
facing issue while npm run setup

### ISSUE THREAD

**Issue by roberts-d** [coryhouse/react-slingshot#668]
node v15.10.0
Python v3.9.2

```
node v15.10.0
Python v3.9.2

```
 react-slingshot@7.0.1 setup
> node tools/setup/setupMessage.js && npm install && node tools/setup/setup.js

===========================
=  React Slingshot Setup  =
===========================

Installing dependencies. Please wait...
npm ERR! code 1
npm ERR! path D:\*****\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files\nodejs\node.exe D:\*****\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'D:\\*****\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@15.10.0 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2.7" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2.7
npm ERR! gyp verb `which` failed     at getNotFoundError (D:\*****\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (D:\*****\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (D:\*****\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at D:\*****\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at D:\*****\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at D:\*****\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:196:21)
npm ERR! gyp verb `which` failed  python2.7 Error: not found: python2.7
npm ERR! gyp verb `which` failed     at getNotFoundError (D:\*****\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (D:\*****\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (D:\*****\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at D:\*****\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at D:\*****\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at D:\*****\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:196:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb could not find "python2.7". checking python launcher
npm ERR! gyp verb could not find "python2.7". guessing location
npm ERR! gyp verb ensuring that file exists: C:\Python27\python.exe
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Can't find Python executable "python2.7", you can set the PYTHON env variable.
npm ERR! gyp ERR! stack     at PythonFinder.failNoPython (D:\*****\node_modules\node-gyp\lib\configure.js:484:19)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (D:\*****\node_modules\node-gyp\lib\configure.js:509:16)
npm ERR! gyp ERR! stack     at D:\*****s\node_modules\graceful-fs\polyfills.js:284:29
npm ERR! gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:196:21)
npm ERR! gyp ERR! System Windows_NT 10.0.18363
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\*****\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd D:\*****\node_modules\node-sass
npm ERR! gyp ERR! node -v v15.10.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\*****\AppData\Local\npm-cache\_logs\2021-03-11T15_53_02_459Z-debug.log
npm ERR! code 1
npm ERR! path D:\*****
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node tools/setup/setupMessage.js && npm install && node tools/setup/setup.js

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\*****\AppData\Local\npm-cache\_logs\2021-03-11T15_53_02_645Z-debug.log
```
```

**Comment by rikongha** [comment]
had errors using node 18, downgraded to node 13 and that was the charm.

**Comment by flyfy1** [comment]
faced the same issue... but don't want to downgrade my node version
